### ISSUE TITLE
Mapping of ISO 19103 to 19115-3/gco/Record not correct

### ISSUE THREAD

**Issue by ejbleys** [ISO-TC211/schemas#13]

**Comment by ejbleijs** [comment]
It has been suggested that  an XML implementation schema be generated for ISO 19103 to represent the sub-components of Record
RecordType currently typed as CharacterString 
Record <<interface>>
   type [0..1] RecordType
   field [1..*]
RecordType <<interface>>
   fieldType [1..*] FieldType
Field <<interface>>
   value         CharacterString
   type [0..*] FieldType
FieldType <<interface>>
   fieldName CharacterString
   fieldType  TypeName

**Comment by PeterParslow** [comment]
Will there be a similar thing for pretty much everything in Clause 7 of ISO 19103 - all the core data types?

Exceptions could be where ISO 19139-1 and ISO 19136 Annex E agree on a mapping that doesn't require a UML class. I haven't checked if there are any.

**Comment by ejbleys** [comment]
Peter
Peter wrote:
> Will there be a similar thing for pretty much everything in Clause 7 of ISO 19103 - all the core data types?
> 

Response:

All Clause 7 will be managed

Peter wrote:
> Exceptions could be where ISO 19139-1 and ISO 19136 Annex E agree on a mapping that doesn't require a UML class. I haven't checked if there are any.
> 

Response:
Yes/No - As the existing standards will not be amended purely for this, no exceptions are required
Once those standards are updated, the changes would be applied in those amendments/updates

Cheers
e
Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ejbleys@gmail.com
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ejbleijs@gmail.com

**Comment by PeterParslow** [comment]
"Exceptions": I was meaning things like ISO 19103 CharacterString, which both ISO 19139-1 (7.8.2) & ISO 19136 (Table D.2) map to xs:string.

I thought that would mean that those parts of ISO 19103 Clause 7 won't need to be represented by XML schema fragments.

**Comment by ejbleys** [comment]
Sorry my misunderstanding
We should adopt xs: types wherever available
E
Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ejbleys@gmail.com
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ejbleijs@gmail.com
