### ISSUE TITLE
Fix `schemaLocation` paths that points to non-existing paths on standards.iso.org

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/schemas#26]
In #24 it is now known that some schema files on standards.iso.org have been deleted.

We need to update existing schema files in our repo to no longer point there but to a local copy.

_Originally posted by @ronaldtse in https://github.com/ISO-TC211/schemas/issues/24#issuecomment-597990216_

**Comment by ejbleys** [comment]
Opinions please (Not just Ron and Evert)
Local copy? ie relative path 
	Only works in situ
OR
schemaLocation =“https://schemas.isotc211.org/ <https://schemas.isotc211.org/>…”?	
	harder to update WHEN we move again
E
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by ejbleys** [comment]
For those who need to see what it would look like
Here is a ZIP file containing ISO 19139 and ISO 19136 in the directory structure as discussed
using relative paths

Note: 
I have not tried to include ISO 19119
In the XML (.xml & .xsd), I have not changed anything but the schema locations and the layout of the namespace attributes

Cheers
Evert
Evert Bleys
Convenor ISO TC 211 XMG
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by cportele** [comment]
Whatever you do, **don't** include any copy of 19136 / GML schema documents on schemas.isotc211.org. Just reference the normative schemas in the OGC schema repository where OGC has policies and processes in place to maintain permanent availability and include bugfixes as needed. Everything else are broken or outdated copies like the ones previously on standards.iso.org.

----
**Resolution 959: Schema files for ISO 19136, Geographic information -- Geography Markup Language (GML)**
Noting that the official XML schema repository for ISO 19136-1 Edition 1 will be http://schemas.opengis.net/gml/3.2.1/, ISO/TC 211 instructs the secretariat to take required actions to delete outdated schema files for ISO 19136 from standards.iso.org.

**Comment by ejbleys** [comment]
Thanks
Will do
I’ll look for the appropriate schema locations
Cheers
Evert

**Comment by PeterParslow** [comment]
As Clemens says, where we are importing schemas that are managed by other groups, we should reference them at their URLs. I think the same principle could be usefully applied where on TC211 standard imports a schema from another TC211 standard. In my view, relative paths are for where the package/schema file being imported is part of the same standard.

Of course, that gives some ambiguity for ISO 19136 / GML - but that is resolved by the Foreword & informative annex C of 19136-1 stating that the schemas are at http://schemas.opengis.net/gml/3.2.1/ (in 19136:2007 it's "only" in the Annex and examples). So (as you'd expect) Clemens is correct.

But as I've said on the other issues & pull requests that refer to this issue, there are many people "out there" who refer to the standards.iso.org locations that have worked for many years.

It's one thing to ensure that we have our own copy safely tucked away, but it is more urgent for our users to work with ISO to get them to reinstate the resources they have removed. Or if that is a strategic refusal (rather than a mistake), to work with us to communicate the change to a large existing user base - or else take a real hit to their credibility for managing IT resources.

I have emailed Mats asking him to contact them.

**Comment by MartinePaepen** [comment]
Hi,
we are implementing ISO 19115-2:2019-01.
And face the same problem:
the spec indicates that the online schema is availalbe on https://standards.iso.org/iso/19115/-2/gmi/
however if we use these, our INSPIRE metadata files doesn't validate due to the missing schema locations at http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/

For us it is necessary to solve this quickly. Any idea how to cope with this in the short term?

Many Thanks!
Martine Paepen (VITO / Belgium)

**Comment by ronaldtse** [comment]
Looks like this is no longer an issue since 19139 has returned? @ejbleys please feel free to close if it is the case. Thanks!

**Comment by PeterParslow** [comment]
@ronaldtse , where has it returned to? It's not at the "previously most authoritative place", https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/

If https://standards.iso.org/iso/19139/ is now considered the right place, then there are still schema import issues to solve (both for TC211 and others - INSPIRE, OGC,...)

**Comment by ronaldtse** [comment]
@PeterParslow bad wording on my part. It has been "re-inserted" (commit: 842920a533e7b8ddd8a95c95a6a3bb6f373f6ace) to schemas.isotc211.org .

This issue was originally meant to address missing schemaLocations sent out to standards.iso.org. 

> If https://standards.iso.org/iso/19139/ is now considered the right place, then there are still schema import issues to solve (both for TC211 and others - INSPIRE, OGC,...)

This still applies...

**Comment by ronaldtse** [comment]
I did a search in the repo, and these schemaLocations are no longer around:

http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19136_Schemas/gml.xsd (point to http://schemas.opengis.net/gml/3.2.1/ ?)

http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gco/gco.xsd
http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd
http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmx/gmx.xsd

We should probably update these to reflect the new resolvable location.

And we should have a place on the website to show where the authoritative schemas are located to prevent user confusion!

**Comment by ejbleys** [comment]
Hi Guys
The only authoritative space is
https://schemas.isotc211.org <https://schemas.isotc211.org/>

Cheers
E
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by PeterParslow** [comment]
Note: the same problem also affects the schemaLocation attributes in the code lists e.g. https://schemas.isotc211.org/schemas/19139/resources/gmxCodelists.xml - which are ours to fix.

**Comment by ejbleys** [comment]
These now, appropriately, reside in https://schemas.isotc211.org/19139/-/ <https://schemas.isotc211.org/19139/-/>
Cheers
e
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by PeterParslow** [comment]
@ejbleys OK - but why do we also host a set with the unhelpful schemaLocations, at the URL I gave?

After I posted this, Mats let me know that ISO have redirected the old 19139 location on their site to https://standards.iso.org/iso/19139/

**Comment by ejbleys** [comment]
Hi Peter
I see what you mean
Anyone on the XMG is at liberty to help fix them

Cheers
E
Evert Bleys
Only the Convenor ISO / TC 211 XMG
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ejbleys@gmail.com
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ejbleijs@gmail.com

**Comment by ejbleys** [comment]
Hi Guys
The appropriate URL for that code list is
https://schemas.isotc211.org/19139/-/resources/codelist/gmxCodelists.xml <https://schemas.isotc211.org/19139/-/resources/codelist/gmxCodelists.xml>
Cheers
E
Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ejbleys@gmail.com
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ejbleijs@gmail.com

**Comment by ejbleys** [comment]
ISO 19136 has been retired use GML
The ISO 19139 XSDs were lost, once they were recovered, they have been extracted, schemaLocations adjusted and placed into the agreed location 
The appropriate location for those XSDs are:
https://schemas.isotc211.org/19139/-/gmd/1.0/gmd.xsd <https://schemas.isotc211.org/19139/-/gmd/1.0/gmd.xsd> 
https://schemas.isotc211.org/19139/-/gmd/1.0/gmd.xsd <https://schemas.isotc211.org/19139/-/gmd/1.0/gmd.xsd> 
https://schemas.isotc211.org/19139/-/gmx/1.0/gmx.xsd <https://schemas.isotc211.org/19139/-/gmx/1.0/gmx.xsd> 

Cheers
E
Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ejbleys@gmail.com
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ejbleijs@gmail.com

**Comment by ejbleys** [comment]
Dear All
https://schemas.isotc211.org/<standardNo>/-<partNo>/<nameSpaceAbreviation>/<versionNo>/???.xsd <https://schemas.isotc211.org/%3CstandardNo%3E/-%3CpartNo%3E/%3CnameSpaceAbreviation%3E/%3CversionNo%3E/???.xsd> 
is the appropriate place
TC 211 has undertaken to maintain schemas in those locations until:
     	the base URL changes (but the structure would be retained)
	we stop supporting XML

Cheers
E
Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ejbleys@gmail.com
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ejbleijs@gmail.com

**Comment by ejbleys** [comment]
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com
