### ISSUE TITLE
Deployment trigger failed

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/schemas#28]
@CAMOBAP795 issue found:

- Your workflow file was invalid: The pipeline is not valid. .github/workflows/deploy.yml (Line: 13, Col: 13): Unrecognized named-value: 'event_type'. Located at position 1 within expression: event_type

Can you please help?

_Originally posted by @ronaldtse in https://github.com/ISO-TC211/schemas/pull/27#issuecomment-599391468_

**Comment by CAMOBAP** [comment]
@ronaldtse  Could you please enable debug logging? https://github.com/actions/toolkit/blob/master/docs/action-debugging.md#how-to-access-step-debug-logs

**Comment by ronaldtse** [comment]
Fixed now. Thanks!
