### ISSUE TITLE
Invalid schema at https://schemas.isotc211.org/19115/-3/md2/2.0/md2.xsd

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/schemas#31]
From Mr. Wern Yir Tsai:

> I open the URL (https://schemas.isotc211.org/19115/-3/md2/2.0/md2.xsd) directly with the XML software,
> the XML software shows the error message as follows.
>    "The schema doesn't appear to be valid by itself."
>    "File https://schemas.isotc211.org/19115/-3/gco/1.0/baseTypes2014.xsd is not valid."
>     (Please see the attached file: " 1-md2 is invalid.png ")

> But I verify the "baseTypes2014.xsd" , it is valid.
>     (Please see the attached file: " 2-baseTypes2014 is valid.png " )

> Would you mind checking the "md2.xsd" if it has any error between the linked schemas ? 

![2-baseTypes2014 is valid](https://user-images.githubusercontent.com/11865/78972298-0332b680-7b40-11ea-994d-46eecf03a011.png)

![1-md2 is invalid](https://user-images.githubusercontent.com/11865/78972300-03cb4d00-7b40-11ea-9797-9e9f193e3d7d.png)

**Comment by PeterParslow** [comment]
Oxygen fails to validate them, with a different reason - an HTTPS certificate issue:

![image](https://user-images.githubusercontent.com/8492193/79205741-3cb43c00-7e36-11ea-8a21-c0207a097cad.png)

**Comment by PeterParslow** [comment]
More usefully, I remember this from XMLSpy years ago - it sometimes gets in a muddle with all the circular imports, when it thinks it has detected some kind of clash between two different definitions of the same thing.

Although here the message is claiming the gco:nilReason is declared twice in the same file - presumably it hasn't coped with that file being imported twice.

Perhaps one of the files, somewhere, is using 'import' where it should be 'include' (or the other way round!). Not sure how to easily check that across all the files.

**Comment by ejbleys** [comment]
Are you using one of the Saxon engine?
Cheers
E
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by PeterParslow** [comment]
I had Oxygen set to use Xerces; set to Saxon gives the same certificate error. But perhaps the question wasn't addressed to me....

**Comment by ejbleys** [comment]
Hi Peter
It was, are you using Saxon EE?
E
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by PeterParslow** [comment]
Evert,
Those are the two choices in Oxygen: Xerces or Saxon EE. But given it hits a certificate error, it hasn’t got that far.

Peter Parslow
OS Open Standards Lead
Adanac Drive, Southampton, United Kingdom, SO16 0AS
T: +44 (0)2380 055341 | M: +44 (0)7796 610020
www.os.uk<http://os.uk/> | peter.parslow@os.uk<mailto:peter.parslow@os.uk>

**Comment by ejbleys** [comment]
Hi Peter
Di I understand what is happening - NO

Cheers
E
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by ejbleys** [comment]
problem seems .to have been resolved
