### ISSUE TITLE
XSDs have links to non-existing XSD files

### ISSUE THREAD

**Issue by Intelligent2013** [ISO-TC211/schemas#33]
These XSDs have a links to the non-existing XSD:
1. `19157\-\mdq\1.2.0\dataQualityResult.xsd` -> `19136/-/gmw/1.1.0/gmw.xsd~ (**fixed** earlier in [commit](https://github.com/ISO-TC211/schemas/commit/b230fede20bd39501a535dc027431d4f092f17f7#diff-d3f24ef229d8aed6eab7f67d40881801c8b441851937238bc21a1e2fcd34ffdf))
2. `19130\-1\smi\1.1.0\groundControlPoints.xsd` -> `19163/-1/igd/1.1.0/igd.xsd` (**fixed**)
3. `19130\-1\smi\1.1.0\groundControlPoints.xsd` -> `19163/-1/igd/1.1.0/IE_ImageryAndGriddedData.xsd` (**fixed**)
4. `19130\-1\smi\1.1.0\nonPhysicalSensorModel.xsd` -> `19163/-1/igd/1.1.0/IE_ImageryAndGriddedData.xsd` (**fixed**)
5. `19157\-\dqm\1.2.0\dqm.xsd` -> `19135/-2/pre/1.2.0/pre.xsd`
6. `19157\-\dqm\1.2.0\qualityMeasures.xsd` -> `19135/-2/pre/1.2.0/pre.xsd`
7. `19163\-2\igd\1.2.0\IE_ImageryAndGriddedData.xsd` -> `19136/-/gmw/1.1.1/gmlWrapperTypes.xsd` (**fixed**)
8. `19163\-2\igd\1.2.0\IE_ThematicGriddedData.xsd` -> `19136/-/gmw/1.1.1/gmlWrapperTypes.xsd` (**fixed**)

**Comment by ronaldtse** [comment]
This is blocking ISO-TC211/schemas.isotc211.org#18.

**Comment by ronaldtse** [comment]
@Intelligent2013 can you help fix these with a PR? Thanks.

**Comment by Intelligent2013** [comment]
I have a question regarding issues:
5. `19157\-\dqm\1.2.0\dqm.xsd` -> `19135/-2/pre/1.2.0/pre.xsd`
6. `19157\-\dqm\1.2.0\qualityMeasures.xsd` -> `19135/-2/pre/1.2.0/pre.xsd`

In repository there isn't folder `19135/-2/pre/1.2.0`, only `19135/-2/pre/1.0`.
@ronaldtse  @ejbleijs  Can I change a link to `19135/-2/pre/1.0/pre.xsd` (i.e. decrease a version) ?

**Comment by ejbleys** [comment]
I’ll check it out today

Evert Bleys
4 Tudor Place
HUGHES ACT
Australia
Mob: 0411 483 876

**Comment by ejbleys** [comment]
Need to check ALL namespace URI declarations

Evert Bleys
4 Tudor Place
HUGHES ACT
Australia
Mob: 0411 483 876

**Comment by ejbleys** [comment]
19163-2\igd\1.2.0\
removed
Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***

**Comment by Intelligent2013** [comment]
FYI, my changes (in the branch issue/33) here: https://github.com/ISO-TC211/schemas/commit/e317640ad23318432ad439b7f8e105ad128428bd
(except issues 5 and 6)

**Comment by Intelligent2013** [comment]
PR created https://github.com/ISO-TC211/schemas/pull/40

**Comment by Intelligent2013** [comment]
For 19135/-2/pre/1.0/pre.xsd I've changed namespace to `http://standards.iso.org/iso/19135/-2/pre/1.0`.

**Comment by ejbleijs** [comment]
Thanks
Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***

**Comment by ronaldtse** [comment]
#40 is merged. Anything further to do here @Intelligent2013 ?

**Comment by Intelligent2013** [comment]
@ronaldtse everything looks ok now. Thank you!
