### ISSUE TITLE
XSDs with duplicated declaration of types

### ISSUE THREAD

**Issue by Intelligent2013** [ISO-TC211/schemas#34]
Some XSDs have duplicated declaration of types (via xsd:import). For example, `19115/-3/mda/1.0/mda.xsd`:
Error:
```
File http://standards.iso.org/iso/19115/-3/gco/1.0/baseTypes2014.xsd has errors.
		'gco:AbstractObject_Type' is already declared.
in schems: https://schemas.isotc211.org/19115/-3/gco/1.0/baseTypes.xsd
```

List of XSDs with such issue:
- ~19115/-3/mda/1.0/mda.xsd~ (_ignore issue, because there is version 2.0_)
- ~19115/-3/mda/1.0/metadataApplication.xsd~ (_ignore issue, because there is version 2.0_)
- 19115/-3/mda/2.0/mda.xsd
- 19115/-3/mda/2.0/metadataApplication.xsd
- ~19115/-3/mrc/1.0/mrc.xsd~ (_ignore issue, because there is version 2.0_)
- ~19115/-3/mrc/1.0/content.xsd~ (_ignore issue, because there is version 2.0_)
- ~19115/-3/mrc/1.0/contentInformationImagery.xsd~ (_ignore issue, because there is version 2.0_)
- 19115/-3/mrc/2.0/mrc.xsd
- 19115/-3/mrc/2.0/content.xsd
- 19115/-3/mrc/2.0/contentInformationImagery.xsd
- ~19115/-3/md1/1.0/md1.xsd~  (_ignore issue, because there is version 2.0_)
- ~19115/-3/md1/1.0/metadataWExtendedType.xsd~  (_ignore issue, because there is version 2.0_)
- 19115/-3/md1/2.0/md1.xsd
- 19115/-3/md1/2.0/metadataWExtendedType.xsd
- ~19115/-3/mds/1.0/metadataDataServices.xsd~ (_ignore issue, because there is version 2.0_)
- ~19115/-3/mds/1.0/mds.xsd~ (_ignore issue, because there is version 2.0_)
- 19115/-3/mds/2.0/metadataDataServices.xsd
- 19115/-3/mds/2.0/mds.xsd
- ~19115/-3/md2/1.0/metadataWithExtensions.xsd~  (_ignore issue, because there is version 2.0_)
- ~19115/-3/md2/1.0/md2.xsd~ (_ignore issue, because there is version 2.0_)
- 19115/-3/md2/2.0/metadataWithExtensions.xsd
- 19115/-3/md2/2.0/md2.xsd
- ~19115/-3/mdt/1.0/mdt.xsd~ (_ignore issue, because there is version 2.0_)
- ~19115/-3/mdt/1.0/metadataTransfer.xsd~ (_ignore issue, because there is version 2.0_)
- 19115/-3/mdt/2.0/mdt.xsd
- 19115/-3/mdt/2.0/metadataTransfer.xsd
- 19165/gpm/1.0/gpm.xsd
- 19165/gpm/1.0/geospatialPreservationMetadata.xsd
- 19131/-1/dps/2.0/dps.xsd

**Comment by ronaldtse** [comment]
This is blocking ISO-TC211/schemas.isotc211.org#18.

**Comment by ronaldtse** [comment]
@Intelligent2013 can you help fix these with a PR? Thanks.

**Comment by Intelligent2013** [comment]
In XSDs there are 3 types of links to another XSDs:
1. relative path:
```xml
<xs:import namespace=... schemaLocation="../../../../19103/-/gco/1.2.0/gco.xsd"/>
```
2. absolute path to https://schemas.isotc211.org:
```xml
<import namespace=... schemaLocation="https://schemas.isotc211.org/19115/-3/gco/1.0/gco.xsd"/>
```
3. absolute path to http://standards.iso.org:
```
<import namespace=... schemaLocation="http://standards.iso.org/iso/19115/-3/gco/1.0/gco.xsd"/>
```

As I understand, types 1 and 2 are equal, because https://schemas.isotc211.org is a mirror of this repository.

Regarding type 3, as soon XSD opens any another XSD from site http://standards.iso.org, then all paths evaluate from http://standards.iso.org, not from https://schemas.isotc211.org (or local disk). Between https://schemas.isotc211.org and http://standards.iso.org there is difference, for example:
- in schema https://schemas.isotc211.org/19115/-3/gco/1.0/gco.xsd:
```xml
<xs:include schemaLocation="baseTypes.xsd"/>
```
- in schema https://standards.iso.org/iso/19115/-3/gco/1.0/gco.xsd:
```xml
<xs:include schemaLocation="baseTypes2014.xsd"/>
```

What is difference between https://schemas.isotc211.org and https://standards.iso.org? Can we replace all links to https://schemas.isotc211.org?

**Comment by ejbleys** [comment]
Will deal later today 
Type 3 should not exist 
...2014 exists because it did - should continue


Evert Bleys
4 Tudor Place
HUGHES ACT
Australia
Mob: 0411 483 876

**Comment by ejbleys** [comment]
this is probably round tripping - that is allowed
name=“AbstractObject_Type” is declared in
https://schemas.isotc211.org/19103/-/gco/1.2.0/baseTypes.xsd
https://schemas.isotc211.org/19115/-3/gco/1.0/baseTypes.xsd
https://schemas.isotc211.org/19115/-3/gco/1.0/baseTypes2014.xsd
https://schemas.isotc211.org/19139/-/gco/1.0/gcoBase.xsd
There is no direct or indirect interactions between these files

Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***

**Comment by ejbleys** [comment]
Type 1 could be converted into type 2 if you prefer
There are pros and cons for each

Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***

**Comment by ronaldtse** [comment]
@ejbleys for type 3, the only issue here is with `schemaLocation`. Why don't we change all the `https://standards.iso.org/...` to `https://schemas.isotc211.org/...`? It doesn't affect the namespace or the usage of the schema. `schemaLocation` in any case is technically provided as an informative hint.

**Comment by ejbleys** [comment]
GitHub has been updated
Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***

**Comment by ronaldtse** [comment]
@ejbleys I can't see the GH update, was it pushed? Thanks.

**Comment by Intelligent2013** [comment]
> this is probably round tripping - that is allowed name=“AbstractObject_Type” is declared in https://schemas.isotc211.org/19103/-/gco/1.2.0/baseTypes.xsd https://schemas.isotc211.org/19115/-3/gco/1.0/baseTypes.xsd https://schemas.isotc211.org/19115/-3/gco/1.0/baseTypes2014.xsd https://schemas.isotc211.org/19139/-/gco/1.0/gcoBase.xsd There is no direct or indirect interactions between these files

@ejbleys yes, between these files there isn't interactions directly. But via another XSDs we get the case, when:
- one imported XSD (let's say "A") pointed to baseTypes.xsd, and 
- another imported XSD (let's say "B") pointed to baseTypes2014.xsd
- 19115/-3/mda/2.0/mda.xsd pointed to "A" XSD and "B" XSD, i.e. 19115/-3/mda/2.0/mda.xsd imported both "baseTypes.xsd" and "baseTypes2014.xsd", and we get duplicated declarations.

I've checked my proposal  (change `http://standards.iso.org/` to `https://schemas.isotc211.org/`) on a few above noticed xsd, and the issue was gone.

**Comment by ejbleys** [comment]
Still?
Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***

**Comment by Intelligent2013** [comment]
> Still?

@ejbleys yes, there is a links to 'schemaLocation="http://standards.iso.org/iso...'
- 19110\fcc\1.0\fcc.xsd:
```xml
<import namespace="http://standards.iso.org/iso/19110/gfc/1.1" schemaLocation="http://standards.iso.org/iso/19110/gfc/1.1/gfc.xsd"/>
```

- 19131\-1\dps\2.0\dps.xsd:
```xml
	<import namespace="http://standards.iso.org/iso/19115/-3/gco/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/gco/1.0/gco.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/cit/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/cit/1.0/citation.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mrl/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mrl/1.0/lineage.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mco/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mco/1.0/constraints.xsd"/>
	<import namespace="http://standards.iso.org/iso/19157/-2/mdq/1.0" schemaLocation="http://standards.iso.org/iso/19157/-2/mdq/1.0/dataQualityElement.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mas/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mas/1.0/applicationSchema.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mrc/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mrc/1.0/content.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mri/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mri/1.0/identification.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mcc/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mcc/1.0/commonClasses.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/gex/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/gex/1.0/extent.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/lan/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/lan/1.0/language.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mmi/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mmi/1.0/maintenance.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mrs/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mrs/1.0/referenceSystem.xsd"/>
```
- 19165\gpm\1.0\geospatialPreservationMetadata.xsd:
```xml
	<import namespace="http://standards.iso.org/iso/19115/-3/cit/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/cit/1.0/cit.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/gco/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/gco/1.0/gco.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mas/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mas/1.0/mas.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mcc/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mcc/1.0/mcc.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mco/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mco/1.0/mco.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mdb/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mdb/1.0/mdb.xsd"/>
	<import namespace="http://standards.iso.org/iso/19157/-2/mdq/1.0" schemaLocation="http://standards.iso.org/iso/19157/-2/mdq/1.0/mdq.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mpc/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mpc/1.0/mpc.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mrc/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mrc/1.0/mrc.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mrd/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mrd/1.0/mrd.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mri/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mri/1.0/mri.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mrl/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mrl/1.0/mrl.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/mrs/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/mrs/1.0/mrs.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/msr/1.0" schemaLocation="http://standards.iso.org/iso/19115/-3/msr/1.0/msr.xsd"/>
	<import namespace="http://standards.iso.org/iso/19115/-3/srv/2.0" schemaLocation="http://standards.iso.org/iso/19115/-3/srv/2.0/srv.xsd"/>

```
I see at master branch.

**Comment by Intelligent2013** [comment]
PR created https://github.com/ISO-TC211/schemas/pull/39

**Comment by Intelligent2013** [comment]
Done. Closing.
