### ISSUE TITLE
XSDs in 19115/-3/gcx/1.0 have components with the same names

### ISSUE THREAD

**Issue by Intelligent2013** [ISO-TC211/schemas#35]
XSDs `19115/-3/gcx/1.0/extendedTypes_autoFromShapeChange.xsd` and `19115/-3/gcx/1.0/extendedTypes.xsd` contain two global components with the same name (via included xsd)

Error:
```
schema contains two global components with the same name FileName_Type, FileName,FileName_PropertyType,
MimeFileType_Type, MimeFileType, MimeFileType_PropertyType, Anchor_Type, Anchor, Anchor_PropertyType
```

**Comment by ronaldtse** [comment]
This is blocking ISO-TC211/schemas.isotc211.org#18.

**Comment by ronaldtse** [comment]
@Intelligent2013 can you help fix these with a PR? Thanks.

**Comment by Intelligent2013** [comment]
Main schema in 19115/-3/gcx/1.0/gcx.xsd has link to extendedTypes.xsd, but not to extendedTypes_autoFromShapeChange.xsd. And there isn't any schema with link to extendedTypes_autoFromShapeChange.xsd.
So there isn't issue here. Closing.

**Comment by ejbleys** [comment]
sorry
this comes from my predecessor
i have no knowledge
i believe it is excess to requirements
unused, unusable

e
Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***

**Comment by ronaldtse** [comment]
File removed in #38.
