### ISSUE TITLE
XSD 19115/-3/msr/1.0/spatialRepresentationImagery.xsd references to the undeclared elements/types

### ISSUE THREAD

**Issue by Intelligent2013** [ISO-TC211/schemas#36]
In `19115/-3/msr/1.0/spatialRepresentationImagery.xsd` there are a references to undeclared elements/types:
- msr:MD_Georectified
- msr:MD_Georectified_Type
- msr:MD_Georeferenceable
- msr:MD_Georeferenceable_Type

**Comment by ronaldtse** [comment]
This is blocking ISO-TC211/schemas.isotc211.org#18.

**Comment by ronaldtse** [comment]
@Intelligent2013 aren't these defined in :

https://github.com/ISO-TC211/schemas/blob/b70b661369619800a91bef0f32484f18780c17ec/19115/-3/msr/1.0/spatialRepresentationImagery.xsd
?

**Comment by ronaldtse** [comment]
Oh, this is `msr/1.0`...

**Comment by Intelligent2013** [comment]
@ronaldtse  there are only references, but aren't declarations.
But here is a note from Altova XmlSpy:
![image](https://user-images.githubusercontent.com/5559926/113614121-bef6cb00-965a-11eb-8be5-90e29010dab2.png)

May be we shouldn't build xsd documentation for this xsd, because it's a part of another xsd, i.e. it isn't standalone xsd?
But how to determine for which of XSDs we need to build xsd documentation?

**Comment by ejbleys** [comment]
I will look at the code, but current version is .../19115/-1/msr/1.3.0/msr.xsd


Evert Bleys
4 Tudor Place
HUGHES ACT
Australia
Mob: 0411 483 876

**Comment by ronaldtse** [comment]
@Intelligent2013 we can only build documentation for valid XSDs, so let’s keep a separate file (YAML) to contain the list of XSD files we want to build. 

@ejbleys if we encounter errors in non-current XSDs, should we correct them or should we let them linger on?

**Comment by ejbleys** [comment]
commission errors - correct
omissions errors - ignore
E 
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
***@***.***
Skype ***@***.***

**Comment by ejbleys** [comment]
Corrected in
	https://github.com/ISO-TC211/schemas/blob/master/19115/-3/msr/1.0/spatialRepresentation.xsd
	https://github.com/ISO-TC211/schemas/blob/master/19115/-3/msr/2.0/spatialRepresentation.xsd
	https://github.com/ISO-TC211/schemas/blob/master/19115/-1/msr/1.3.0/spatialRepresentation.xsd
had not correctly element:substitutionGroup= and extension:base= to msr:AbstractMD_SpatialRepresentation (was msr:MD_SpatialRepresentation)

Cheers
e
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
***@***.***
Skype ***@***.***

**Comment by Intelligent2013** [comment]
> @Intelligent2013 we can only build documentation for valid XSDs, so let’s keep a separate file (YAML) to contain the list of XSD files we want to build.

@ronaldtse I've added a file schemas.yml processing for list of XSD files (in https://github.com/ISO-TC211/schemas.isotc211.org/pull/19)

**Comment by ronaldtse** [comment]
Thanks @ejbleys and @Intelligent2013 . @Intelligent2013 is this issue done now?

**Comment by ejbleys** [comment]
Hi Ron
I believe it is sorted
E

Evert Bleys
4 Tudor Place
HUGHES ACT
Australia
Mob: 0411 483 876

**Comment by Intelligent2013** [comment]
Yes, fixed. Thank you. Closing.

**Comment by ronaldtse** [comment]
Thanks!
