### ISSUE TITLE
List out schemas available and their namespaces

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/schemas#41]
Some ISO/TC 211 schemas use `schemas.isotc211.org` but some use `standards.iso.org` in namespaces.

I wonder if we should list all available schemas out and also their namespaces (which are like their IDs) on the front page for developers?

Ping @ejbleys

**Comment by ejbleys** [comment]
Seems reasonable
The namespaces were in the (few) HTMLs I generated (I think also in all 19115)
E

Evert Bleys
4 Tudor Place
HUGHES ACT
Australia
Mob: 0411 483 876

**Comment by ronaldtse** [comment]
Thanks @ejbleys !

We'll work on that.

**Comment by ejbleys** [comment]
If it is useful, I can provide a hand made version that identifies imported and included namespaces
As a result I can see 19115/-3/cit/2.0 imports 19115/-3/lan/1.0 which imports 19115/-3/cit/1.0
E

Evert Bleys
4 Tudor Place
HUGHES ACT
Australia
Mob: 0411 483 876

**Comment by ronaldtse** [comment]
@ejbleys It's been two years since we last discussed this topic. Maybe we can make it happen? 😉
