### ISSUE TITLE
Schema browser issues (19139 first edition)

### ISSUE THREAD

**Issue by PeterParslow** [ISO-TC211/schemas#44]
The schema browser (left hand pane) at https://schemas.isotc211.org/schemas/19139/ no longer lists the file metadataEntity.xsd; the file does appear in its location (https://schemas.isotc211.org/schemas/19139/-/gmd/1.0/metadataEntity.xsd), but you cannot browse to it.

Also, the schema browser (left hand pane) at https://schemas.isotc211.org/schemas/19139/ now contains a lot of .svg files.

Perhaps this is deliberate, but they do not render, and they make it very hard to find the actual schemas. It looks more like all of the image files for all of the index pages are present in every folder.

The experience would be improved if the arrows in the tree actually collapsed the tree - at present, they have a "mouse over" behaviour that turns the pointer to a finger, which leads to the expectation that clicking will achieve something.

(So I guess that's actually three issues!)

**Comment by ronaldtse** [comment]
@PeterParslow apologies for this we are still experimenting with the best way in exposing schema documentation.

The SVG files are meant to load at the front-page links, e.g.:
https://schemas.isotc211.org/19139/-/gco/1.0/gco/

I think we will move the documentation to another location...

**Comment by ronaldtse** [comment]
Ping @strogonoff @Intelligent2013

**Comment by PeterParslow** [comment]
> 
> The SVG files are meant to load at the front-page links, e.g.:
> https://schemas.isotc211.org/19139/-/gco/1.0/gco/

These look good, and I assumed the images were for the index pages (although there are a lot more svg files than images)
> 
> I think we will move the documentation to another location...

Or perhaps just the images, leaving the index files to be found by browsing.

**Comment by Intelligent2013** [comment]
@ronaldtse what if we rename `diagrams` to `.diagrams` and make changes in `jekyll-theme-isotc211/_includes/resource-tree-item.html` for ignoring items starting on `.`? It will looks as `hidden` file/folder in *nix systems.
