### ISSUE TITLE
gco/baseTypes.xsd vs gco/gco.xsd

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/schemas#49]
We currently have these files for `gco`:

* https://github.com/ISO-TC211/schemas/blob/master/19103/-/gco/1.2.0/baseTypes.xsd
* https://github.com/ISO-TC211/schemas/blob/master/19103/-/gco/1.2.0/gco.xsd

`gco.xsd` is purely a wrapper over `baseTypes.xsd` with extra annotation and an import of `baseTypes.xsd`:

https://github.com/ISO-TC211/schemas/blob/c91c7ccc4829111b33ff20490876561fcfeae065/19103/-/gco/1.2.0/gco.xsd#L9-L13

In terms of usage:

~~`gco.xsd` is only imported by two other schemas:~~ (UPDATE: there are more)
* 19103/-/gcx/1.2.0/extendedTypes.xsd
* 19123/-/cis/1.1.0/gridPoint.xsd

~~`baseTypes.xsd` is only imported by two schemas:~~ (UPDATE: there are more)
* 19103/-/gco/1.2.0/gco.xsd (the gco schema)
* 19123/-/cis/1.1.0/gridPoint.xsd

Notice that `19123/-/cis/1.1.0/gridPoint.xsd` imports both the wrapping `gco.xsd` AND the `baseTypes.xsd`, which I assume is an error.

Could we consolidate the `gco.xsd` and `baseTypes.xsd` schemas into a single one?

**Comment by ejbleys** [comment]
I would not combine the two at this time as TC211/WG 1 is V likely to be reviewing ISO 19103 in the near future and may well expand the references in gco.xsd.
I believe that .../19103/-/gco/1.2.0/gco.xsd is use in a multitude of schemas
It is reasonable to resolve the 19123/-/cit/1.1.0/gridPoint.xsd circular referencing issue

**Comment by ronaldtse** [comment]
> I would not combine the two at this time as TC211/WG 1 is V likely to be reviewing ISO 19103 in the near future and may well expand the references in gco.xsd.

True...

> It is reasonable to resolve the 19123/-/cit/1.1.0/gridPoint.xsd circular referencing issue

Cool. Should we keep `baseTypes.xsd` or `gco.xsd`?

**Comment by ejbleys** [comment]
I see 63 occurrences of …/19103/-/gco/1.2.0/gco.xsd

Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***

**Comment by ronaldtse** [comment]
@ejbleys indeed I missed some references on double checking now! But actually many of those are from index.html files.

And the double import of `gco.xsd` and `baseTypes.xsd` is also more pronounced.

**Comment by ronaldtse** [comment]
Double imports:
* 19130/-2/smi/1.1.0/spatialElements.xsd
* 19130/-2/smi/1.1.0/sensorParameters.xsd
* 19130/-2/smi/1.1.0/codeList.xsd
* 19130/-1/smi/1.1.0/spatialElements.xsd
* 19130/-1/smi/1.1.0/physicalSensorModel.xsd
* 19130/-1/smi/1.1.0/groundControlPoints.xsd
* 19130/-1/smi/1.1.0/codeList.xsd
* 19123/-/cis/3.1.0/gridPoint.xsd
* 19123/-/cis/3.1.0/codeLists.xsd
* 19123/-/cis/1.1.0/gridPoint.xsd
* 19123/-/cis/1.1.0/codeLists.xsd
* 19123/-/cis/1.1.0/cis-0.xsd

**Comment by ejbleys** [comment]
Not in HTMLs (filtered on .xsd)
But gco PLUS baseTypes - issue accepted
Should drop baseTypes if get gco from parent
Can you find - I could, but judging by some of your recent amazing achievements, it might be easier for you.

Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***

**Comment by ejbleys** [comment]
Thanks
I will deal

Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***

**Comment by ronaldtse** [comment]
@ejbleys up to you! Happy to make a PR for it if you'd like me to do it.

**Comment by ejbleys** [comment]
Have updated in GitHub XML for testing
Ready to update GitHub Schemas once testing done

Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***

**Comment by ronaldtse** [comment]
Thank you @ejbleys !

**Comment by ronaldtse** [comment]
@ejbleys are the new changes ready to go? Thanks!

**Comment by ejbleys** [comment]
Later today
Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***

**Comment by ejbleys** [comment]
I believe this has been resolved: gco.xsd + baseTypes.xsd -> gco.xsd

**Comment by ronaldtse** [comment]
@ejbleys there are a few files that still refer to `19103/-/gco/1.2.0/baseTypes.xsd`:

```
19136/-1/gmw/1.1.0/gmlWrapperTypes.xsd: <xs:import namespace="https://schemas.isotc211.org/19103/-/gco/1.2" schemaLocation="../../../../19103/-/gco/1.2.0/baseTypes.xsd"/>
19163/-1/igd/1.1.0/IE_Imagery.xsd:      <xs:import namespace="https://schemas.isotc211.org/19103/-/gco/1.2" schemaLocation="../../../../19103/-/gco/1.2.0/baseTypes.xsd"/>
19163/-1/igd/1.1.0/IE_ImageryAndGriddedData.xsd:    <xs:import namespace="https://schemas.isotc211.org/19103/-/gco/1.2" schemaLocation="../../../../19103/-/gco/1.2.0/baseTypes.xsd"/>
19163/-1/igd/1.1.0/IE_ThematicGriddedData.xsd:    <xs:import namespace="https://schemas.isotc211.org/19103/-/gco/1.2" schemaLocation="../../../../19103/-/gco/1.2.0/baseTypes.xsd"/>
```

Should we change those to just `gco.xsd` too?

**Comment by ejbleys** [comment]
Do not unless also referencing gco.xsd. Logically they could, but referencing basicTypes.xsd is perfectly appropriate, so long as they do not also reference gco.xsd.
E
Evert Bleys
4 Tudor Place
HUGHES ACT
Australia
Mob: 0411 483 876

**Comment by ronaldtse** [comment]
While such usage is valid, it is a bit strange to reference `baseTypes.xsd` when the schema points to `gco` and that all other schemas already use `gco.xsd`. 

The logic goes as follows:

1. `<xs:import namespace="https://schemas.isotc211.org/19103/-/gco/1.2"/>` is fine by itself because `schemaLocation` is optional.
2. If we add `schemaLocation` to the `xs:import` statement, it would likely be expected to be `schemaLocation="https://schemas.isotc211.org/19103/-/gco/1.2.0/gco.xsd"`

Moreover, since `schemaLocation` is informative, changing the schemaLocation does not change the schema?

I think I'm just advocating the consolidation of baseTypes.xsd and gco.xsd because the latter is a pure wrapper with no content of its own...

**Comment by ejbleys** [comment]
I believe all these have been resolved now

**Comment by ronaldtse** [comment]
Thanks @ejbleys !
