### ISSUE TITLE
Report: site not updating on pushes

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/schemas#65]
From @ejbleys 

I am wondering why material in the GitHub TC211 schemas repository is not being migrated to TC211 repository. 

I did see a “not authorized” flag pop up in the script run.

The https://github.com/ISO-TC211/schemas-isotc211.github.io repository is supposed to automatically deploy on pushes to this current repository.

@kwkwan can you please help check? Thanks.

**Comment by kwkwan** [comment]
PAT has been updated and the deploy action can be triggered successfully.

**Comment by ronaldtse** [comment]
Thanks @kwkwan !

**Comment by ejbleys** [comment]
Thanks
Evert Bleys
4 Tudor Place
HUGHES ACT 2605
Australia
email:  ***@***.***
Mob:   +61 (0)411 483 876
Land:  +61 (0)2 6281 1773
Skype: ***@***.***
